<<<<<<< HEAD
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
Authentification_token:
    path:     api/login
    methods:  ['POST']
=======
create:
  path: /api/users
  controller: App\Controller\UserController::addUser
  methods: ['POST']

authentification_token:
  path: /api/login
  methods: ['POST']

>>>>>>> master
